image: ruby:3.3

pages:
  stage: build
  script:
    - bundle install --path vendor
    - bundle exec jekyll build -d public
  artifacts:
    paths:
    - public
    expire_in: 1 week
  rules:
  - if: $CI_PIPELINE_SOURCE == "scheduled"
  - if: $CI_COMMIT_BRANCH == "main
